# Generated by Django 5.0 on 2023-12-31 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_alter_patient_age_alter_patient_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.therapist'),
        ),
    ]
