# Generated by Django 5.0 on 2023-12-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_alter_sessions_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
