# Generated by Django 5.0 on 2023-12-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_sessions_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='therapist',
        ),
        migrations.AddField(
            model_name='sessions',
            name='therapist',
            field=models.ManyToManyField(blank=True, to='module1.therapist'),
        ),
    ]
