# Generated by Django 5.0 on 2023-12-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_remove_sessions_therapist_sessions_therapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.CharField(max_length=3),
        ),
    ]
