# Generated by Django 5.0 on 2024-01-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0006_alter_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='date_time',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
        ),
    ]
