# Generated by Django 5.0 on 2024-01-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0007_sessions_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='date_time',
            new_name='default_datetime',
        ),
        migrations.AddField(
            model_name='bookedsession',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookedsession',
            name='selected_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
