# Generated by Django 5.0 on 2024-01-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_rename_date_time_sessions_default_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedsession',
            name='paypal_payment_id',
        ),
    ]
