# Generated by Django 5.0 on 2024-01-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0010_remove_bookedsession_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='session_type',
            field=models.CharField(default='Regular', max_length=50),
        ),
    ]
