# Generated by Django 5.0 on 2024-01-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0011_alter_bookedsession_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='session_type',
            field=models.CharField(blank=True, default='Regular', max_length=50, null=True),
        ),
    ]
