# Generated by Django 5.0 on 2024-01-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0012_alter_bookedsession_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='selected_time',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
    ]
