# Generated by Django 5.0 on 2024-01-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0013_alter_bookedsession_selected_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsession',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
