# Generated by Django 5.0 on 2024-01-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0015_remove_bookedsession_notification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfeedback',
            name='answer1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='answer2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='answer3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='answer4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='answer5',
            field=models.TextField(),
        ),
    ]
