# Generated by Django 5.0 on 2024-01-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0017_patientfeedback_is_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistfeedback',
            name='patient_feedback',
        ),
        migrations.RemoveField(
            model_name='therapistfeedback',
            name='therapist',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
                ('answer4', models.TextField()),
                ('answer5', models.TextField()),
                ('is_viewed', models.BooleanField(default=False)),
                ('booked_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.bookedsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.therapist')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientFeedback',
        ),
        migrations.DeleteModel(
            name='TherapistFeedback',
        ),
    ]
