# Generated by Django 5.0 on 2024-01-10 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0018_remove_therapistfeedback_patient_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
