# Generated by Django 5.0 on 2024-01-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0019_feedback_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreport',
            name='assessment_observation',
        ),
        migrations.AddField(
            model_name='feedback',
            name='total_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
